# Generated by Django 2.0.7 on 2018-07-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_add', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
